language: python
python:
  - "2.6"
  - "2.7"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - sudo python manage.py makemigrations
  - sudo python manage.py migrate
  - sudo python manage.py test