language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE luizalabsteste;'
script: 
  - python manage.py makemigrations
  - python manage.py migrate
  - pytest tests/