# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170326_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='andress',
            options={'verbose_name': 'Andress', 'verbose_name_plural': 'Andresses'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
